github: [moneymanagerex]
patreon: moneymanagerex
tidelift: moneymanagerex/moneymanagerex
custom: ["https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=moneymanagerex%40gmail%2ecom&lc=US&item_name=MoneyManagerEx&no_note=0&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHostedGuest", http://moneymanagerex.org/]
