language: objective-c
compiler:
  - clang
  
before_install:
  - echo $TRAVIS_OS_NAME
  # LINUX
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt install webkitgtk-3.0; fi
  # OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install wxwidgets; fi
before_script:
  - travis_retry ./configure
script:
  - ./configure && make -j4
branches:
  except:
    - legacy
notifications:
  recipients:
    - developers@moneymanagerex.org
  email:
    on_success: change
    on_failure: always
os:
  - osx
