language: objective-c
compiler:
  - clang
  
before_install:
  - brew update
  - brew install wxwidgets
before_script:
  - travis_retry ./configure
script:
  - ./configure && make -j4
branches:
  only:
    - master
    - develop
notifications:
  recipients:
    - moneymanagerex@googlegroups.com
    - nikolay.akimov@gmail.com
    - guanlisheng@gmail.com
  email:
    on_success: change
    on_failure: always
os:
  - osx
