language: objective-c
compiler:
  - clang
  
before_install:
  - brew update
  - brew install wxwidgets
before_script:
  - travis_retry ./configure
script:
  - ./configure && make -j4
branches:
  except:
    - legacy
notifications:
  recipients:
    - developers@moneymanagerex.org
  email:
    on_success: change
    on_failure: always
os:
  - osx
